import Head from 'next/head'

import dynamic from 'next/dynamic'
import {Title} from '@adiranids/react-tailwind'
import '@adiranids/react-tailwind/dist/style.css'

import moment from 'moment'
import admin from 'firebase-admin'
import creds from '../fbservercreds.json'
import {getFirestore} from 'firebase-admin/firestore'
const EventsLayout = dynamic(()=>import(/*webpackChunkName: "eventslayout"*/'../layouts/EventsContainer'))
const EventCard = dynamic(()=>import(/*webpackChunkName:"eventcard"*/'../components/EventCard')) 



export default function Home({events}) {


  return (
    <div>
      <Head>
        <title>Next Course</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>

      <Title size="h1">Our Tech Events</Title>
      <EventsLayout>

        {events.map(event => {
          if(event.event.currency)
          {
            return <EventCard event={event.event} eventID={event.eventID} key={event.eventID} />
          }
        })}
       
      </EventsLayout>

    </div>
  )
}


export async function getStaticProps()
{
  const date = moment().format("YYYY-MM-DD")

  if(admin.apps.length == 0)
  admin.initializeApp({
      credential: admin.credential.cert(creds)
  })

  const db = getFirestore()
 
  let events = []

  const eventsRef = db.collection('events');
  const snapshot = await eventsRef.where('date', '>=', date).get();
  if (snapshot.empty) {
    console.log('No matching documents.');
  }  

  snapshot.forEach(doc => {

    let eve = doc.data()

    events.push({eventID: doc.id, event: {
      name: eve.name,
      image: eve.image || "",
      price: eve.price,
      currency: eve.currency || "",
      date: eve.date
    }
  })
  });


  return {
    props: {
      events: events
    },
    revalidate: 15 * 60
  }

}


